# stage 1
FROM node:latest as node
WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .
RUN npm run build --prod

# stage 2
FROM nginx:alpine
## Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*

COPY --from=node /app/dist/agl-calendar /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

VOLUME /tmp

RUN echo "mainFileName=\"\$(ls /usr/share/nginx/html/main*.js)\" && \
          envsubst '\$BACKEND_API_URL ' < \${mainFileName} > main.tmp && \
          mv main.tmp  \${mainFileName} && nginx -g 'daemon off;'" > run.sh

ENTRYPOINT ["sh", "run.sh"]
