apiVersion: apps/v1
kind: Deployment
metadata:
  name: break-booking-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: break-booking-frontend
  template:
    metadata:
      labels:
        app: break-booking-frontend
    spec:
      containers:
        - name: break-booking-frontend
          image: pkdocker3383/break-booking-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: HOME_URL
              value: "http://120.159.30.85:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: break-booking-frontend
  labels:
    app: break-booking-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: break-booking-frontend
